In [60]:
import numpy as np
np.__version__
import pandas as pd
pd.__version__

'1.2.4'

In [2]:
import os
os.getcwd()
os.chdir('anaconda3\envs\ml-zoomcamp\data') #change dir



In [5]:
df = pd.read_csv('data.csv')
df.head(n=10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

In [56]:
pd.options.display.float_format = '{:20,.2f}'.format #non-scientific view
df.groupby('Make').MSRP.mean() #Question 3

Make
Acura                      34,887.59
Alfa Romeo                 61,600.00
Aston Martin              197,910.38
Audi                       53,452.11
BMW                        61,546.76
Bentley                   247,169.32
Bugatti                 1,757,223.67
Buick                      28,206.61
Cadillac                   56,231.32
Chevrolet                  28,350.39
Chrysler                   26,722.96
Dodge                      22,390.06
FIAT                       22,670.24
Ferrari                   238,218.84
Ford                       27,399.27
GMC                        30,493.30
Genesis                    46,616.67
HUMMER                     36,464.41
Honda                      26,674.34
Hyundai                    24,597.04
Infiniti                   42,394.21
Kia                        25,310.17
Lamborghini               331,567.31
Land Rover                 67,823.22
Lexus                      47,549.07
Lincoln                    42,839.83
Lotus                      69,188

In [19]:
mean_hp_before = df['Engine HP'].mean()  #Question 5
print(round(mean_hp_before))
df.fillna(mean_hp_before)
mean_hp_after = df['Engine HP'].mean()
print(round(mean_hp_after))

#df[df['Year'] >= 2015].isnull().sum() #Question 4
#df.isnull().sum()

249
249


In [67]:
df2 = df[df['Make'] == 'Rolls-Royce']   #Questions 6
x = df2[['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates().to_numpy()
xtx = x.T.dot(x)
print(xtx)
inv = np.linalg.inv(xtx)
print(inv.sum())
#df[['Engine HP', 'Engine Cylinders', 'highway MPG']]

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]
[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]
0.03221232067748617


In [71]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300]) #Questions 7
w = inv.dot(x.T).dot(y)
print(w)

[ 0.19989598 31.02612262 31.65378877]
